using System;
using System.Runtime.Serialization;
using Ibanity.Apis.Client.Utils;

namespace Ibanity.Apis.Client.Products.eInvoicing.Models
{
    /// <summary>
    /// <p>This is an object representing the invoice that can be sent by a supplier. This document is always an UBL in a format supported by CodaBox.</p>
    /// <p>The maximum file size is 100MB.</p>
    /// </summary>
    [DataContract]
    public class PeppolInvoice : Identified<Guid>
    {
        /// <summary>
        /// When this peppol invoice was created. Formatted according to &lt;a href&#x3D;&#39;https://en.wikipedia.org/wiki/ISO_8601&#39;&gt;ISO8601&lt;/a&gt; spec
        /// </summary>
        /// <value>When this peppol invoice was created. Formatted according to &lt;a href&#x3D;&#39;https://en.wikipedia.org/wiki/ISO_8601&#39;&gt;ISO8601&lt;/a&gt; spec</value>
        [DataMember(Name = "createdAt", EmitDefaultValue = false)]
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>
        /// &lt;p&gt;Provides extra information to help you identify what went wrong.&lt;/p&gt;&lt;ul&gt;&lt;li&gt;    &lt;code&gt;invalid-malicious&lt;/code&gt; The integrity of the document could not be verified.&lt;/li&gt;&lt;li&gt;    &lt;code&gt;invalid-format&lt;/code&gt; The format of the document is not supported or the document is not a credit note.&lt;/li&gt;&lt;li&gt;    &lt;code&gt;invalid-xsd&lt;/code&gt; The XSD validation failed for the document.&lt;/li&gt;&lt;li&gt;    &lt;code&gt;invalid-schematron&lt;/code&gt; The schematron validation failed for the document.&lt;/li&gt;&lt;li&gt;&lt;code&gt;invalid-identifiers&lt;/code&gt; The supplier data in the document could not be verified.&lt;/li&gt;&lt;li&gt;    &lt;code&gt;invalid-size&lt;/code&gt; The size of the document exceeds 100MB.&lt;/li&gt;&lt;li&gt;    &lt;code&gt;invalid-type&lt;/code&gt; The document is not an xml.&lt;/li&gt;&lt;li&gt;    &lt;code&gt;error-customer-not-registered&lt;/code&gt; The receiver of the document could not be found on the PEPPOL network.&lt;/li&gt;&lt;li&gt;    &lt;code&gt;error-document-type-not-supported&lt;/code&gt; The receiver does not support the type of document that was sent.&lt;/li&gt;&lt;li&gt;    &lt;code&gt;error-customer-access-point-issue&lt;/code&gt; There was an issue with the access point of the receiver.&lt;/li&gt;&lt;li&gt;    &lt;code&gt;error-general&lt;/code&gt;Unspecified error.&lt;/li&gt;&lt;/ul&gt;
        /// </summary>
        /// <value>&lt;p&gt;Provides extra information to help you identify what went wrong.&lt;/p&gt;&lt;ul&gt;&lt;li&gt;    &lt;code&gt;invalid-malicious&lt;/code&gt; The integrity of the document could not be verified.&lt;/li&gt;&lt;li&gt;    &lt;code&gt;invalid-format&lt;/code&gt; The format of the document is not supported or the document is not a credit note.&lt;/li&gt;&lt;li&gt;    &lt;code&gt;invalid-xsd&lt;/code&gt; The XSD validation failed for the document.&lt;/li&gt;&lt;li&gt;    &lt;code&gt;invalid-schematron&lt;/code&gt; The schematron validation failed for the document.&lt;/li&gt;&lt;li&gt;&lt;code&gt;invalid-identifiers&lt;/code&gt; The supplier data in the document could not be verified.&lt;/li&gt;&lt;li&gt;    &lt;code&gt;invalid-size&lt;/code&gt; The size of the document exceeds 100MB.&lt;/li&gt;&lt;li&gt;    &lt;code&gt;invalid-type&lt;/code&gt; The document is not an xml.&lt;/li&gt;&lt;li&gt;    &lt;code&gt;error-customer-not-registered&lt;/code&gt; The receiver of the document could not be found on the PEPPOL network.&lt;/li&gt;&lt;li&gt;    &lt;code&gt;error-document-type-not-supported&lt;/code&gt; The receiver does not support the type of document that was sent.&lt;/li&gt;&lt;li&gt;    &lt;code&gt;error-customer-access-point-issue&lt;/code&gt; There was an issue with the access point of the receiver.&lt;/li&gt;&lt;li&gt;    &lt;code&gt;error-general&lt;/code&gt;Unspecified error.&lt;/li&gt;&lt;/ul&gt;</value>
        [DataMember(Name = "errors", EmitDefaultValue = false)]
        public Object Errors { get; set; }

        /// <summary>
        /// &lt;p&gt;The technical status of the invoice.&lt;/p&gt;&lt;p&gt;Possible values&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;code&gt;created&lt;/code&gt; The invoice was successfully received by Flowin e-invoicing and will be processed.&lt;/li&gt;&lt;li&gt;&lt;code&gt;sending&lt;/code&gt; The recipient has started processing the invoice.&lt;/li&gt;&lt;li&gt;&lt;code&gt;sent&lt;/code&gt; The invoice is sent to the Access Point of the customer. In this case you will receive a transmissionId.&lt;/li&gt;&lt;li&gt;&lt;code&gt;acknowledged&lt;/code&gt; The Access Point of the customer has acknowledged the invoice.&lt;/li&gt;&lt;li&gt;&lt;code&gt;accepted&lt;/code&gt; The Access Point of the customer has accepted the invoice.&lt;/li&gt;&lt;li&gt;&lt;code&gt;rejected&lt;/code&gt; The Access Point of the customer has rejected the invoice due to syntactic or semantic issues.&lt;/li&gt;&lt;li&gt;&lt;code&gt;invalid&lt;/code&gt; The invoice is not valid, you will receive an error object containing a code and a message explaining what went wrong (see above).&lt;/li&gt;&lt;li&gt;&lt;code&gt;send-error&lt;/code&gt; The invoice could not be sent to the customer, you will receive an error object containing a code and a message explaining what went wrong (see above).    &lt;/li&gt;&lt;/ul&gt;&lt;p&gt;In case of an unspecified error or an issue with the receiving Access Point, you can try to resend the invoice. Flowin e-invoicing will not automatically resend the invoice.&lt;/p&gt;&lt;p&gt;&lt;code&gt;acknowledged&lt;/code&gt;, &lt;code&gt;accepted&lt;/code&gt;, &lt;code&gt;rejected&lt;/code&gt; and &lt;code&gt;send-error&lt;/code&gt; are final technical statuses of a document.&lt;/p&gt;
        /// </summary>
        /// <value>&lt;p&gt;The technical status of the invoice.&lt;/p&gt;&lt;p&gt;Possible values&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;code&gt;created&lt;/code&gt; The invoice was successfully received by Flowin e-invoicing and will be processed.&lt;/li&gt;&lt;li&gt;&lt;code&gt;sending&lt;/code&gt; The recipient has started processing the invoice.&lt;/li&gt;&lt;li&gt;&lt;code&gt;sent&lt;/code&gt; The invoice is sent to the Access Point of the customer. In this case you will receive a transmissionId.&lt;/li&gt;&lt;li&gt;&lt;code&gt;acknowledged&lt;/code&gt; The Access Point of the customer has acknowledged the invoice.&lt;/li&gt;&lt;li&gt;&lt;code&gt;accepted&lt;/code&gt; The Access Point of the customer has accepted the invoice.&lt;/li&gt;&lt;li&gt;&lt;code&gt;rejected&lt;/code&gt; The Access Point of the customer has rejected the invoice due to syntactic or semantic issues.&lt;/li&gt;&lt;li&gt;&lt;code&gt;invalid&lt;/code&gt; The invoice is not valid, you will receive an error object containing a code and a message explaining what went wrong (see above).&lt;/li&gt;&lt;li&gt;&lt;code&gt;send-error&lt;/code&gt; The invoice could not be sent to the customer, you will receive an error object containing a code and a message explaining what went wrong (see above).    &lt;/li&gt;&lt;/ul&gt;&lt;p&gt;In case of an unspecified error or an issue with the receiving Access Point, you can try to resend the invoice. Flowin e-invoicing will not automatically resend the invoice.&lt;/p&gt;&lt;p&gt;&lt;code&gt;acknowledged&lt;/code&gt;, &lt;code&gt;accepted&lt;/code&gt;, &lt;code&gt;rejected&lt;/code&gt; and &lt;code&gt;send-error&lt;/code&gt; are final technical statuses of a document.&lt;/p&gt;</value>
        [DataMember(Name = "technicalStatus", EmitDefaultValue = false)]
        public string TechnicalStatus { get; set; }

        /// <summary>
        /// &lt;p&gt;The business status of the invoice.&lt;/p&gt;&lt;p&gt;Possible values&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;code&gt;acknowledged&lt;/code&gt; The invoice was successfully acknowledged by the recipient and will be further processed.&lt;/li&gt;&lt;li&gt;&lt;code&gt;in-process&lt;/code&gt; The invoice is valid and will be sent to the customer.&lt;/li&gt;&lt;li&gt;&lt;code&gt;under-query&lt;/code&gt; The recipient will not continue processing the invoice without receveing additional information from the supplier.&lt;/li&gt;&lt;li&gt;&lt;code&gt;conditionally-accepted&lt;/code&gt; The recipient has conditionally accepted the invoice.&lt;/li&gt;&lt;li&gt;&lt;code&gt;rejected&lt;/code&gt; The recipient has rejected the document.&lt;/li&gt;&lt;li&gt;&lt;code&gt;accepted&lt;/code&gt; The recipient has accepted the document.&lt;/li&gt;&lt;li&gt;&lt;code&gt;paid&lt;/code&gt; The recipient indicates that the document has been partially or fully paid.&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;&lt;code&gt;under-query&lt;/code&gt; and &lt;code&gt;conditionally-accepted&lt;/code&gt; and &lt;code&gt;rejected&lt;/code&gt; often require both counterparties to communicate using an external channel for additional clarification.&lt;code&gt;rejected&lt;/code&gt; and &lt;code&gt;paid&lt;/code&gt; are final business statuses of an invoice.&lt;/p&gt;
        /// </summary>
        /// <value>&lt;p&gt;The business status of the invoice.&lt;/p&gt;&lt;p&gt;Possible values&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;code&gt;acknowledged&lt;/code&gt; The invoice was successfully acknowledged by the recipient and will be further processed.&lt;/li&gt;&lt;li&gt;&lt;code&gt;in-process&lt;/code&gt; The invoice is valid and will be sent to the customer.&lt;/li&gt;&lt;li&gt;&lt;code&gt;under-query&lt;/code&gt; The recipient will not continue processing the invoice without receveing additional information from the supplier.&lt;/li&gt;&lt;li&gt;&lt;code&gt;conditionally-accepted&lt;/code&gt; The recipient has conditionally accepted the invoice.&lt;/li&gt;&lt;li&gt;&lt;code&gt;rejected&lt;/code&gt; The recipient has rejected the document.&lt;/li&gt;&lt;li&gt;&lt;code&gt;accepted&lt;/code&gt; The recipient has accepted the document.&lt;/li&gt;&lt;li&gt;&lt;code&gt;paid&lt;/code&gt; The recipient indicates that the document has been partially or fully paid.&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;&lt;code&gt;under-query&lt;/code&gt; and &lt;code&gt;conditionally-accepted&lt;/code&gt; and &lt;code&gt;rejected&lt;/code&gt; often require both counterparties to communicate using an external channel for additional clarification.&lt;code&gt;rejected&lt;/code&gt; and &lt;code&gt;paid&lt;/code&gt; are final business statuses of an invoice.&lt;/p&gt;</value>
        [DataMember(Name = "businessStatus", EmitDefaultValue = false)]
        public string BusinessStatus { get; set; }

        /// <summary>
        /// &lt;p&gt;The status of the invoice.&lt;/p&gt;&lt;p&gt;Possible values&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;code&gt;created&lt;/code&gt; The invoice was successfully received by CodaBox and will be processed.&lt;/li&gt;&lt;li&gt;&lt;code&gt;sending&lt;/code&gt; The invoice is valid and will be sent to the customer.&lt;/li&gt;&lt;li&gt;&lt;code&gt;sent&lt;/code&gt; The invoice is sent to the access point of the customer. In this case you will receive a transmissionId.&lt;/li&gt;&lt;li&gt;&lt;code&gt;invalid&lt;/code&gt; The invoice is not valid, you will receive an error object containing a code and a message explaining what went wrong (see below).&lt;/li&gt;&lt;li&gt;&lt;code&gt;send-error&lt;/code&gt; The invoice could not be sent to the customer, you will receive an error object containing a code and a message explaining what went wrong (see below).    &lt;/li&gt;&lt;/ul&gt;&lt;p&gt;In case of an unspecified error or an issue with the receiving access point, you can try to resend the invoice. CodaBox will not automatically resend the invoice, send-error is a final state of a document.&lt;/p&gt;
        /// </summary>
        /// <value>&lt;p&gt;The status of the invoice.&lt;/p&gt;&lt;p&gt;Possible values&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;code&gt;created&lt;/code&gt; The invoice was successfully received by CodaBox and will be processed.&lt;/li&gt;&lt;li&gt;&lt;code&gt;sending&lt;/code&gt; The invoice is valid and will be sent to the customer.&lt;/li&gt;&lt;li&gt;&lt;code&gt;sent&lt;/code&gt; The invoice is sent to the access point of the customer. In this case you will receive a transmissionId.&lt;/li&gt;&lt;li&gt;&lt;code&gt;invalid&lt;/code&gt; The invoice is not valid, you will receive an error object containing a code and a message explaining what went wrong (see below).&lt;/li&gt;&lt;li&gt;&lt;code&gt;send-error&lt;/code&gt; The invoice could not be sent to the customer, you will receive an error object containing a code and a message explaining what went wrong (see below).    &lt;/li&gt;&lt;/ul&gt;&lt;p&gt;In case of an unspecified error or an issue with the receiving access point, you can try to resend the invoice. CodaBox will not automatically resend the invoice, send-error is a final state of a document.&lt;/p&gt;</value>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        [Obsolete("Prefer 'TechnicalStatus' property")]
        public string Status { get; set; }

        /// <summary>
        /// This is a unique identifier used within the Peppol network. In case of an issue this can be used in communication with the receiving party.
        /// </summary>
        /// <value>This is a unique identifier used within the Peppol network. In case of an issue this can be used in communication with the receiving party.</value>
        [DataMember(Name = "transmissionId", EmitDefaultValue = false)]
        public string TransmissionId { get; set; }
    }
}
