name: Publish
on:
  release:
    types: [published]
jobs:
  publish:
    name: Build and publish NuGet package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Pack
      run: dotnet pack --configuration Release -p:Version=${GITHUB_REF##*/} --output . src/Client/Client.csproj
    - name: Publish
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}}
